{
    'name': 'Estate',
    'version': '19.0.0.0.0',
    'summary': 'Modul Estate untuk belajar Odoo 19',
    'description': 'Modul sederhana untuk manajemen estate.',
    'author': 'Teguh Surya Zulfikar',
    'website': 'https://example.com',
    'category': 'Real Estate',
    'license': 'LGPL-3',
    'depends': ['base'],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'views/estate_property_views.xml',
        'views/estate_property_type_views.xml',
        'views/estate_property_offer_views.xml',
        'views/estate_property_tag_views.xml',
        'views/estate_menu.xml',
    ],
    'demo': [
        'demo/demo.xml',
    ],
    'installable': True,
    'application': True,
}